### ISSUE TITLE
null feature icon throws TypeError

### ISSUE THREAD

**Issue by b2k** [SveltePress/sveltepress#335]
### Describe the bug

Using the default theme, setting a feature icon to null throws an error message.

### Reproduction

Update routes\\+page.md with the following feature changes:

```
features:
  - title: Markdown centered
    description: To help you can start writing with minimal configuration
    icon: null
  - title: Build with Sveltekit
    description: Preserve the full power of Sveltekit. So that you can do more than SSG
  - title: Svelte in Markdown
    description: Feel free to use svelte in markdown. Explore infinite possibilities.
```

### Logs

```shell
TypeError: Cannot read properties of null (reading 'type')
    at Module.Feature [as default] (C:\Users\Brian\Dev\SveltePress\Premium\node_modules\@sveltepress\theme-default\dist\components\home\Feature.svelte:57:22)
```

### Screenshots

```shell

```

### Severity

annoyance
