### ISSUE TITLE
null heroImage throws exception

### ISSUE THREAD

**Issue by b2k** [SveltePress/sveltepress#336]
### Describe the bug

In the default theme, passing `heroImage: null` in the routes\\+page.md throws an exception.

### Reproduction

Set the heroImage to null:

```
---
title: Premium Finance
heroImage: null
tagline: A simple, easy to use Premium Finance System integrated with the full suite of Quotepro Insurance Technologies.
actions:
  - label: View on quotepro.com
    type: primary
    to: https://quoteprosolutions.com/premium-finance
    external: true
features:
  - title: Markdown centered
    description: To help you can start writing with minimal configuration
    icon: null
  - title: Build with Sveltekit
    description: Preserve the full power of Sveltekit. So that you can do more than SSG
    icon: '../Components/NoIcon.svelte'
  - title: Svelte in Markdown
    description: Feel free to use svelte in markdown. Explore infinite possibilities.
    icon: '../Components/NoIcon.svelte'
---
```

### Logs

```shell
TypeError: Cannot read properties of null (reading 'startsWith')
    at Module.parseImageSrc (C:\Users\Brian\Dev\SveltePress\Premium\node_modules\@sveltepress\theme-default\dist\components\utils.js:10:13)
    at Module.HeroImage [as default] (C:\Users\Brian\Dev\SveltePress\Premium\node_modules\@sveltepress\theme-default\dist\components\home\HeroImage.svelte:9:13)
```

### Screenshots

```shell

```

### Severity

annoyance
